// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAa7CSL0ZGq-PHyBlrT9XAv9M6M6wU_-w',
    appId: '1:825131519623:web:c9b4c089407eb379803222',
    messagingSenderId: '825131519623',
    projectId: 'easyfin-b992b',
    authDomain: 'easyfin-b992b.firebaseapp.com',
    storageBucket: 'easyfin-b992b.appspot.com',
    measurementId: 'G-31XSPM2P2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlatglj7mcclwWMuA18Pqg0OEVhwZtnQ',
    appId: '1:825131519623:android:e106677f01665646803222',
    messagingSenderId: '825131519623',
    projectId: 'easyfin-b992b',
    storageBucket: 'easyfin-b992b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4HWzxhzJPHf_DawusV33YGPw0hp0Zco',
    appId: '1:825131519623:ios:f76f22ee3a3e400f803222',
    messagingSenderId: '825131519623',
    projectId: 'easyfin-b992b',
    storageBucket: 'easyfin-b992b.appspot.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4HWzxhzJPHf_DawusV33YGPw0hp0Zco',
    appId: '1:825131519623:ios:47907d9141f51b59803222',
    messagingSenderId: '825131519623',
    projectId: 'easyfin-b992b',
    storageBucket: 'easyfin-b992b.appspot.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
